#!/bin/bash
DESCR=$1
shift
/Users/tberg/thirdparty/run-command-mult $OCT5 "jobs/parse/icsi.conf" "run-command /usr/local/lang/jdk1.6.0-64bit/bin/java -server -ea -Xmx2g -cp ../../parser-0.1-SNAPSHOT-jar-with-dependencies.jar scalanlp.parser.discrim.StructuredTrainer icsi.conf" "$DESCR" ""
